path_to_model = "app/pytorch/draftstars.pt"

path_to_initial_brawler_embeddings = "app/pytorch/b_save.csv"
path_to_adjusted_brawler_embeddings = "app/pytorch/brawler_embeddings.csv"
path_to_map_embeddings = "app/pytorch/map_embeddings.csv"

brawlers = ['SHELLY', 'COLT', 'BULL', 'BROCK', 'RICO', 'SPIKE', 'BARLEY', 'JESSIE', 'NITA', 'DYNAMIKE', 'EL PRIMO', 'MORTIS', 'CROW', 'POCO', 'BO', 'PIPER', 'PAM', 'TARA', 'DARRYL', 'PENNY', 'FRANK', 'GENE', 'TICK', 'LEON', 'ROSA', 'CARL', 'BIBI', '8-BIT', 'SANDY', 'BEA', 'EMZ', 'MR. P', 'MAX', 'empty1', 'JACKY', 'GALE', 'NANI', 'SPROUT', 'SURGE', 'COLETTE', 'AMBER', 'LOU', 'BYRON', 'EDGAR', 'RUFFS', 'STU', 'BELLE', 'SQUEAK', 'GROM', 'BUZZ', 'GRIFF', 'ASH', 'MEG', 'LOLA', 'FANG', 'empty2', 'EVE', 'JANET', 'BONNIE', 'OTIS', 'SAM', 'GUS', 'BUSTER', 'CHESTER', 'GRAY', 'MANDY', 'R-T', 'WILLOW', 'MAISIE', 'HANK', 'CORDELIUS', 'DOUG', 'PEARL', 'CHUCK', 'CHARLIE', 'MICO', 'KIT', 'LARRY & LAWRIE', 'MELODIE', 'ANGELO', 'DRACO', 'LILY', 'BERRY', 'CLANCY', 'MOE', 'KENJI']

# Map list, as interpreted by backend. This is necessary as the model only recognizes indices, which 
# are defined semi-randomly when the model is created.
maps = ["Hard Lane", "Double Swoosh", "Last Stop", "G.G. Mortuary", "Infinite Doom", "Spice Production", "Local Businesses", "Reflections", "Island Hopping", "Sunny Soccer", "Flaring Phoenix", "Beach Ball", "Backyard Bowl", "Offside Trap", "Goldarm Gulch", "Twilight Passage", "Four Levels", "New Horizons", "Minecart Madness", "Kaboom Canyon", "Coconut Cove", "Safe Zone", "Center Stage", "Belle's Rock", "Retina", "Hot Potato", "Spider Crawler", "Gem Fort", "Out in the Open", "Diamond Dome", "Rustic Arcade", "Dueling Beetles", "Double Locking", "Slayer's Paradise", "Sneaky Sneak", "Ring of Fire", "Deep End", "Between the Rivers", "Undermine", "Pinball Dreams", "Ahead of the Curve", "Deathcap Trap", "Parallel Plays", "Sneaky Fields", "Open Space", "Hard Rock Mine", "Super Beach", "Goalkeeper's Dream", "Acute Angle", "Open Business", "Penalty Kick", "Dragon Jaws",  "Canal Grande", "Hideout", "Shooting Star"]

# This remains constant.
maps_according_to_frontend = ["Undermine", "G.G. Mortuary", "Gem Fort", "Ahead of the Curve", "Between the Rivers", "Pinball Dreams", "Four Levels", "Sneaky Sneak", "Super Beach", "Double Locking", "Dragon Jaws", "Infinite Doom", "Center Stage", "Rustic Arcade", "Double Swoosh", "Hot Potato", "Goldarm Gulch", "Deathcap Trap", "Local Businesses", "Backyard Bowl", "Belle's Rock", "Flaring Phoenix", "Hard Lane", "Retina", "New Horizons", "Acute Angle", "Parallel Plays", "Open Business", "Coconut Cove", "Reflections", "Slayer's Paradise", "Island Hopping", "Diamond Dome", "Sneaky Fields", "Twilight Passage", "Spice Production", "Dueling Beetles", "Offside Trap", "Goalkeeper's Dream", "Hard Rock Mine", "Penalty Kick", "Last Stop", "Out in the Open", "Minecart Madness", "Open Space", "Sunny Soccer", "Deep End", "Safe Zone", "Ring of Fire", "Beach Ball", "Kaboom Canyon", "Spider Crawler", "Canal Grande", "Hideout", "Shooting Star"]
