path_to_model = "app/pytorch/draftstars.pt"
path_to_brawler_embeddings = "app/pytorch/brawler_embeddings.csv"
path_to_map_embeddings = "app/pytorch/map_embeddings.csv"

brawlers = ['SHELLY', 'COLT', 'BULL', 'BROCK', 'RICO', 'SPIKE', 'BARLEY', 'JESSIE', 'NITA', 'DYNAMIKE', 'EL PRIMO', 'MORTIS', 'CROW', 'POCO', 'BO', 'PIPER', 'PAM', 'TARA', 'DARRYL', 'PENNY', 'FRANK', 'GENE', 'TICK', 'LEON', 'ROSA', 'CARL', 'BIBI', '8-BIT', 'SANDY', 'BEA', 'EMZ', 'MR. P', 'MAX', 'empty1', 'JACKY', 'GALE', 'NANI', 'SPROUT', 'SURGE', 'COLETTE', 'AMBER', 'LOU', 'BYRON', 'EDGAR', 'RUFFS', 'STU', 'BELLE', 'SQUEAK', 'GROM', 'BUZZ', 'GRIFF', 'ASH', 'MEG', 'LOLA', 'FANG', 'empty2', 'EVE', 'JANET', 'BONNIE', 'OTIS', 'SAM', 'GUS', 'BUSTER', 'CHESTER', 'GRAY', 'MANDY', 'R-T', 'WILLOW', 'MAISIE', 'HANK', 'CORDELIUS', 'DOUG', 'PEARL', 'CHUCK', 'CHARLIE', 'MICO', 'KIT', 'LARRY & LAWRIE', 'MELODIE', 'ANGELO', 'DRACO', 'LILY', 'BERRY', 'CLANCY', 'MOE', 'KENJI']

# Map list, as interpreted by backend. This is necessary as the model only recognizes indices, which 
# are defined semi-randomly when the model is created.
# If you create your own model, this must be updated. This list only applies to the one linked in the README.
maps = [
"Local Businesses", "Penalty Kick", "New Horizons", "Between the Rivers", "Close Quarters", "Out in the Open", "Beach Ball", "Acute Angle", "Minecart Madness", "Parallel Plays", "Offside Trap", "Hard Lane", "Deep End", "Bridge Too Far", "Sneaky Fields", "Pinball Dreams", "Flaring Phoenix", "Hot Potato", "The Great Open", "Bear Trap", "Sneaky Sneak", "Twilight Passage", "Hard Rock Mine", "Center Stage", "Undermine", "Dueling Beetles", "Diamond Dome", "Back Pocket", "Goldarm Gulch", "Safe Zone", "Encirclement", "Four Levels", "Gem Fort", "Retina", "Ahead of the Curve", "Super Beach", "Sunny Soccer", "Open Space", "Sunset Spar", "Double Swoosh", "Open Business", "Rustic Arcade", "Backyard Bowl", "Island Hopping", "Last Stop", "Secret or Mystery", "Shooting Star", "Triple Dribble", "Ring of Fire", "Belle's Rock", "Misty Meadows", "Snake Prairie", "Kaboom Canyon", 
]
# Only change this if the data in frontend/src/data/brawlers.js is rearranged
maps_according_to_frontend = ["Undermine", "G.G. Mortuary", "Gem Fort", "Ahead of the Curve", "Between the Rivers", "Pinball Dreams", "Four Levels", "Sneaky Sneak", "Super Beach", "Double Locking", "Dragon Jaws", "Infinite Doom", "Center Stage", "Rustic Arcade", "Double Swoosh", "Hot Potato", "Goldarm Gulch", "Deathcap Trap", "Local Businesses", "Backyard Bowl", "Belle's Rock", "Flaring Phoenix", "Hard Lane", "Retina", "New Horizons", "Acute Angle", "Parallel Plays", "Open Business", "Coconut Cove", "Reflections", "Slayer's Paradise", "Island Hopping", "Diamond Dome", "Sneaky Fields", "Twilight Passage", "Spice Production", "Dueling Beetles", "Offside Trap", "Goalkeeper's Dream", "Hard Rock Mine", "Penalty Kick", "Last Stop", "Out in the Open", "Minecart Madness", "Open Space", "Sunny Soccer", "Deep End", "Safe Zone", "Ring of Fire", "Beach Ball", "Kaboom Canyon", "Spider Crawler", "Canal Grande", "Hideout", "Shooting Star"]
