export const maps = [{
  "name": "Undermine",
  "game_mode": "0",
  "imgUrl": "Undermine.webp",
  "id": "0",
},
{
  "name": "G.G. Mortuary",
  "game_mode": "4",
  "imgUrl": "G.G.-Mortuary.webp",
  "id": "1",
},
{
  "name": "Gem Fort",
  "game_mode": "0",
  "imgUrl": "Gem-Fort.webp",
  "id": "2",
},
{
  "name": "Ahead of the Curve",
  "game_mode": "0",
  "imgUrl": "Ahead-Of-The-Curve.webp",
  "id": "3",
},
{
  "name": "Between the Rivers",
  "game_mode": "2",
  "imgUrl": "Between-The-Rivers.webp",
  "id": "4",
},
{
  "name": "Pinball Dreams",
  "game_mode": "1",
  "imgUrl": "Pinball-Dreams.webp",
  "id": "5",
},
{
  "name": "Four Levels",
  "game_mode": "2",
  "imgUrl": "Four-Levels.webp",
  "id": "6",
},
{
  "name": "Sneaky Sneak",
  "game_mode": "0",
  "imgUrl": "Sneaky-Sneak.webp",
  "id": "7",
},
{
  "name": "Super Beach",
  "game_mode": "1",
  "imgUrl": "Super-Beach.webp",
  "id": "8",
},
{
  "name": "Double Locking",
  "game_mode": "4",
  "imgUrl": "Double-Locking.webp",
  "id": "9",
},
{
  "name": "Dragon Jaws",
  "game_mode": "2",
  "imgUrl": "Dragon-Jaws.webp",
  "id": "10",
},
{
  "name": "Infinite Doom",
  "game_mode": "3",
  "imgUrl": "Infinite-Doom.webp",
  "id": "11",
},
{
  "name": "Center Stage",
  "game_mode": "1",
  "imgUrl": "Center-Stage.webp",
  "id": "12",
},
{
  "name": "Rustic Arcade",
  "game_mode": "0",
  "imgUrl": "Rustic-Arcade.webp",
  "id": "13",
},
{
  "name": "Double Swoosh",
  "game_mode": "0",
  "imgUrl": "Double-Swoosh.webp",
  "id": "14",
},
{
  "name": "Hot Potato",
  "game_mode": "4",
  "imgUrl": "Hot-Potato.webp",
  "id": "15",
},
{
  "name": "Goldarm Gulch",
  "game_mode": "2",
  "imgUrl": "Goldarm-Gulch.webp",
  "id": "16",
},
{
  "name": "Deathcap Trap",
  "game_mode": "0",
  "imgUrl": "Deathcap-Trap.webp",
  "id": "17",
},
{
  "name": "Local Businesses",
  "game_mode": "5",
  "imgUrl": "Local-Businesses.webp",
  "id": "18",
},
{
  "name": "Backyard Bowl",
  "game_mode": "1",
  "imgUrl": "Backyard-Bowl.webp",
  "id": "19",
},
{
  "name": "Belle's Rock",
  "game_mode": "2",
  "imgUrl": "Belle's-Rock.webp",
  "id": "20",
},
{
  "name": "Flaring Phoenix",
  "game_mode": "2",
  "imgUrl": "Flaring-Phoenix.webp",
  "id": "21",
},
{
  "name": "Hard Lane",
  "game_mode": "2",
  "imgUrl": "Hard-Lane.webp",
  "id": "22",
},
{
  "name": "Retina",
  "game_mode": "0",
  "imgUrl": "Retina.webp",
  "id": "23",
},
{
  "name": "New Horizons",
  "game_mode": "2",
  "imgUrl": "New-Horizons.webp",
  "id": "24",
},
{
  "name": "Acute Angle",
  "game_mode": "0",
  "imgUrl": "Acute-Angle.webp",
  "id": "25",
},
{
  "name": "Parallel Plays",
  "game_mode": "5",
  "imgUrl": "Parallel-Plays.webp",
  "id": "26",
},
{
  "name": "Open Business",
  "game_mode": "5",
  "imgUrl": "Open-Business.webp",
  "id": "27",
},
{
  "name": "Coconut Cove",
  "game_mode": "3",
  "imgUrl": "Coconut-Cove.webp",
  "id": "28",
},
{
  "name": "Reflections",
  "game_mode": "5",
  "imgUrl": "Reflections.webp",
  "id": "29",
},
{
  "name": "Slayer's Paradise",
  "game_mode": "3",
  "imgUrl": "Slayers-Paradise.webp",
  "id": "30",
},
{
  "name": "Island Hopping",
  "game_mode": "2",
  "imgUrl": "Island-Hopping.webp",
  "id": "31",
},
{
  "name": "Diamond Dome",
  "game_mode": "4",
  "imgUrl": "Diamond-Dome.webp",
  "id": "32",
},
{
  "name": "Sneaky Fields",
  "game_mode": "1",
  "imgUrl": "Sneaky-Fields.webp",
  "id": "33",
},
{
  "name": "Twilight Passage",
  "game_mode": "2",
  "imgUrl": "Twilight-Passage.webp",
  "id": "34",
},
{
  "name": "Spice Production",
  "game_mode": "3",
  "imgUrl": "Spice-Production.webp",
  "id": "35",
},
{
  "name": "Dueling Beetles",
  "game_mode": "5",
  "imgUrl": "Dueling-Beetles.webp",
  "id": "36",
},
{
  "name": "Offside Trap",
  "game_mode": "1",
  "imgUrl": "Offside-Trap.webp",
  "id": "37",
},
{
  "name": "Goalkeeper's Dream",
  "game_mode": "1",
  "imgUrl": "Goalkeeper's-Dream.webp",
  "id": "38",
},
{
  "name": "Hard Rock Mine",
  "game_mode": "0",
  "imgUrl": "Hard-Rock-Mine.webp",
  "id": "39",
},
{
  "name": "Penalty Kick",
  "game_mode": "1",
  "imgUrl": "Penalty-Kick.webp",
  "id": "40",
},
{
  "name": "Last Stop",
  "game_mode": "0",
  "imgUrl": "Last-Stop.webp",
  "id": "41",
},
{
  "name": "Out in the Open",
  "game_mode": "2",
  "imgUrl": "Out-In-The-Open.webp",
  "id": "42",
},
{
  "name": "Minecart Madness",
  "game_mode": "0",
  "imgUrl": "Minecart-Madness.webp",
  "id": "43",
},
{
  "name": "Open Space",
  "game_mode": "0",
  "imgUrl": "Open-Space.webp",
  "id": "44",
},
{
  "name": "Sunny Soccer",
  "game_mode": "1",
  "imgUrl": "Sunny-Soccer.webp",
  "id": "45",
},
{
  "name": "Deep End",
  "game_mode": "2",
  "imgUrl": "Deep-End.webp",
  "id": "46",
},
{
  "name": "Safe Zone",
  "game_mode": "4",
  "imgUrl": "Safe-Zone.webp",
  "id": "47",
},
{
  "name": "Ring of Fire",
  "game_mode": "5",
  "imgUrl": "Ring-Of-Fire.webp",
  "id": "48",
},
{
  "name": "Beach Ball",
  "game_mode": "1",
  "imgUrl": "Beach-Ball.webp",
  "id": "49",
},
{
  "name": "Kaboom Canyon",
  "game_mode": "4",
  "imgUrl": "Kaboom-Canyon.webp",
  "id": "50",
},
{
  "name": "Spider Crawler",
  "game_mode": "1",
  "imgUrl": "Spider-Crawler.webp",
  "id": "51",
}]